# Generated by CypressEditor
# 21/01/2020, 9:28:26 AM

# THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
# PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
# FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
model BasicBuilder -ndm 2 -ndf 3;



#define units
set mm  1.0;
set m   [expr 1000*$mm]
set N   1.0;
set kN  [expr 1000*$N]
set s   1.0;
set MPa  [expr $N/pow($mm,2)]
set GPa  [expr 1000*$MPa]
set g [expr 9.81*$m/pow($s,2)]
set Ubig 1.e10;             # a really large number
set Usmall [expr 1/$Ubig];      # a really small number


puts "assigning nodes"


#Define widths and heights
set H1 [expr 3750*$mm];
set H2 [expr 3000*$mm];
set H3 [expr 3000*$mm];

set W [expr 8400*$mm];


# Define levels
set Y1 0.;
set Y2 $H1;
set Y3 [expr $H1 + $H2];
set Y4 [expr $H1 + (2.*$H2)];
set Y5 [expr $H1 + (3.*$H2)];
set Y6 [expr $H1 + (4.*$H2)];
set Y7 [expr $H1 + (5.*$H2)];
set Y8 [expr $H1 + (6.*$H2)];

#define bays 
set X1 0.;
set X2 $W;
set X3 [expr 2.*$W];
set X4 [expr 3.*$W];


#Half of column depth 
set hcol [expr 228.6*$mm];

#Define coordinates for offsets 
set XX1  [expr $X1 + $hcol];
set XX2  [expr $X2 - $hcol];
set XX3  [expr $X2 + $hcol];
set XX4  [expr $X3 - $hcol];
set XX5  [expr $X3 + $hcol];
set XX6  [expr $X4 - $hcol];


# define nodes
node 1 $X1 $Y1;
node 2 $X2 $Y1;
node 3 $X3 $Y1;
node 4 $X4 $Y1;

node 5 $X1 $Y2;
node 6 $X2 $Y2;
node 7 $X3 $Y2;
node 8 $X4 $Y2;

node 9 $X1 $Y3;
node 10 $X2 $Y3;
node 11 $X3 $Y3;
node 12 $X4 $Y3;

node 13 $X1 $Y4;
node 14 $X2 $Y4;
node 15 $X3 $Y4;
node 16 $X4 $Y4;

node 17 $X1 $Y5;
node 18 $X2 $Y5;
node 19 $X3 $Y5;
node 20 $X4 $Y5;

node 21 $X1 $Y6;
node 22 $X2 $Y6;
node 23 $X3 $Y6;
node 24 $X4 $Y6;

node 25 $X1 $Y7;
node 26 $X2 $Y7;
node 27 $X3 $Y7;
node 28 $X4 $Y7;

node 29 $X1 $Y8;
node 30 $X2 $Y8;
node 31 $X3 $Y8;
node 32 $X4 $Y8;





##Define secondary nodes 
node 1001 $X1 $Y1;
node 1002 $X2 $Y1;
node 1003 $X3 $Y1;
node 1004 $X4 $Y1;
#
node 1011 $X1 $Y2;
node 1012 $X2 $Y2;
node 1013 $X3 $Y2;
node 1014 $X4 $Y2;

node 1015 $X1 $Y2;
node 1016 $X2 $Y2;
node 1017 $X3 $Y2;
node 1018 $X4 $Y2;
#
node 1021 $X1 $Y3;
node 1022 $X2 $Y3;
node 1023 $X3 $Y3;
node 1024 $X4 $Y3;
#
node 1025 $X1 $Y3;
node 1026 $X2 $Y3;
node 1027 $X3 $Y3;
node 1028 $X4 $Y3;
#
node 1031 $X1 $Y4;
node 1032 $X2 $Y4;
node 1033 $X3 $Y4;
node 1034 $X4 $Y4;
#
node 1035 $X1 $Y4;
node 1036 $X2 $Y4;
node 1037 $X3 $Y4;
node 1038 $X4 $Y4;

node 1041 $X1 $Y5;
node 1042 $X2 $Y5;
node 1043 $X3 $Y5;
node 1044 $X4 $Y5;

node 1045 $X1 $Y5;
node 1046 $X2 $Y5;
node 1047 $X3 $Y5;
node 1048 $X4 $Y5;

node 1051 $X1 $Y6;
node 1052 $X2 $Y6;
node 1053 $X3 $Y6;
node 1054 $X4 $Y6;
#
node 1055 $X1 $Y6;
node 1056 $X2 $Y6;
node 1057 $X3 $Y6;
node 1058 $X4 $Y6;

node 1061 $X1 $Y7;
node 1062 $X2 $Y7;
node 1063 $X3 $Y7;
node 1064 $X4 $Y7;
#
node 1065 $X1 $Y7;
node 1066 $X2 $Y7;
node 1067 $X3 $Y7;
node 1068 $X4 $Y7;

node 1071 $X1 $Y8;
node 1072 $X2 $Y8;
node 1073 $X3 $Y8;
node 1074 $X4 $Y8;
#

#Nodes for rigid elements
node 2001 $XX1 $Y2
node 2002 $XX2 $Y2
node 2003 $XX3 $Y2
node 2004 $XX4 $Y2
node 2005 $XX5 $Y2
node 2006 $XX6 $Y2

node 3001 $XX1 $Y3
node 3002 $XX2 $Y3
node 3003 $XX3 $Y3
node 3004 $XX4 $Y3
node 3005 $XX5 $Y3
node 3006 $XX6 $Y3

node 4001 $XX1 $Y4
node 4002 $XX2 $Y4
node 4003 $XX3 $Y4
node 4004 $XX4 $Y4
node 4005 $XX5 $Y4
node 4006 $XX6 $Y4

node 5001 $XX1 $Y5
node 5002 $XX2 $Y5
node 5003 $XX3 $Y5
node 5004 $XX4 $Y5
node 5005 $XX5 $Y5
node 5006 $XX6 $Y5

node 6001 $XX1 $Y6
node 6002 $XX2 $Y6
node 6003 $XX3 $Y6
node 6004 $XX4 $Y6
node 6005 $XX5 $Y6
node 6006 $XX6 $Y6

node 7001 $XX1 $Y7
node 7002 $XX2 $Y7
node 7003 $XX3 $Y7
node 7004 $XX4 $Y7
node 7005 $XX5 $Y7
node 7006 $XX6 $Y7

node 8001 $XX1 $Y8
node 8002 $XX2 $Y8
node 8003 $XX3 $Y8
node 8004 $XX4 $Y8
node 8005 $XX5 $Y8
node 8006 $XX6 $Y8


#Nodes for beam hinges elements
node    2011    $XX1    $Y2
node    2012    $XX2    $Y2
node    2013    $XX3    $Y2
node    2014    $XX4    $Y2
node    2015    $XX5    $Y2
node    2016    $XX6    $Y2
            
node    3011    $XX1    $Y3
node    3012    $XX2    $Y3
node    3013    $XX3    $Y3
node    3014    $XX4    $Y3
node    3015    $XX5    $Y3
node    3016    $XX6    $Y3
            
node    4011    $XX1    $Y4
node    4012    $XX2    $Y4
node    4013    $XX3    $Y4
node    4014    $XX4    $Y4
node    4015    $XX5    $Y4
node    4016    $XX6    $Y4
            
node    5011    $XX1    $Y5
node    5012    $XX2    $Y5
node    5013    $XX3    $Y5
node    5014    $XX4    $Y5
node    5015    $XX5    $Y5
node    5016    $XX6    $Y5
            
node    6011    $XX1    $Y6
node    6012    $XX2    $Y6
node    6013    $XX3    $Y6
node    6014    $XX4    $Y6
node    6015    $XX5    $Y6
node    6016    $XX6    $Y6
            
node    7011    $XX1    $Y7
node    7012    $XX2    $Y7
node    7013    $XX3    $Y7
node    7014    $XX4    $Y7
node    7015    $XX5    $Y7
node    7016    $XX6    $Y7
            
node    8011    $XX1    $Y8
node    8012    $XX2    $Y8
node    8013    $XX3    $Y8
node    8014    $XX4    $Y8
node    8015    $XX5    $Y8
node    8016    $XX6    $Y8





# BOUNDARY CONDITIONS
fix 1 1 1 1
fix 2 1 1 1
fix 3 1 1 1
fix 4 1 1 1


#nodal mass
mass    5   17.122  0   0
mass    6   34.244  0   0
mass    7   34.244  0   0
mass    8   17.122  0   0
                
mass    9   17.122  0   0
mass    10  34.244  0   0
mass    11  34.244  0   0
mass    12  17.122  0   0
                
mass    13  17.122  0   0
mass    14  34.244  0   0
mass    15  34.244  0   0
mass    16  17.122  0   0
                
mass    17  17.122  0   0
mass    18  34.244  0   0
mass    19  34.244  0   0
mass    20  17.122  0   0
                
mass    21  17.122  0   0
mass    22  34.244  0   0
mass    23  34.244  0   0
mass    24  17.122  0   0
                
mass    25  17.122  0   0
mass    26  34.244  0   0
mass    27  34.244  0   0
mass    28  17.122  0   0
                
mass    29  17.122  0   0
mass    30  34.244  0   0
mass    31  34.244  0   0
mass    32  17.122  0   0




puts "nodes assignment complete"




puts "reading elastic section properties"

# define section tags:
set ColSecTag 1
set BeamSecTag 2

set Ec [expr 24*$GPa]

# set up geometric transformations of element
set IDColTransf 1; # all columns
set IDBeamTransf 2; # all beams

geomTransf Linear $IDColTransf
geomTransf Linear $IDBeamTransf

# Define beam sections 
set HBeam [expr 914*$mm];
set BBeam [expr 457*$mm];
set AgBeam [expr $HBeam*$BBeam];
set IzBeam [expr 0.3*1./12.*$BBeam*pow($HBeam,3)];



# Define column sections 
set HCol [expr 457*$mm];
set BCol [expr 457*$mm];
set AgCol [expr $HCol*$BCol];



set IzCol_1 [expr 0.33*1./12.*$BCol*pow($HCol,3)];
set IzCol_2 [expr 0.43*1./12.*$BCol*pow($HCol,3)];
set IzCol_3 [expr 0.55*1./12.*$BCol*pow($HCol,3)];
set IzCol_4 [expr 0.7*1./12.*$BCol*pow($HCol,3)];
set IzCol_5 [expr 0.374*1./12.*$BCol*pow($HCol,3)];



# 

#Define rigid element for beam-column joint 
set IzBc [expr 1./12.*$BBeam*pow($HBeam,3)];
set EBc [expr 24000000*$GPa];

puts "finished reading elastic section properties"


puts "assembling sections"

# define elastic beam connectivity 

element elasticBeamColumn   201 2011    2012    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   202 2013    2014    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   203 2015    2016    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   301 3011    3012    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   302 3013    3014    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   303 3015    3016    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   401 4011    4012    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   402 4013    4014    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   403 4015    4016    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   501 5011    5012    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   502 5013    5014    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   503 5015    5016    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   601 6011    6012    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   602 6013    6014    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   603 6015    6016    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   701 7011    7012    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   702 7013    7014    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   703 7015    7016    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   801 8011    8012    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   802 8013    8014    $AgBeam $Ec $IzBeam $IDBeamTransf   ;
element elasticBeamColumn   803 8015    8016    $AgBeam $Ec $IzBeam $IDBeamTransf   ;




puts "elastic beams assembled" 




puts "assembling rigid zones"

element elasticBeamColumn   2001    5   2001    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   2002    2002    6   $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   2003    6   2003    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   2004    2004    7   $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   2005    7   2005    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   2006    2006    8   $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   3001    9   3001    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   3002    3002    10  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   3003    10  3003    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   3004    3004    11  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   3005    11  3005    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   3006    3006    12  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   4001    13  4001    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   4002    4002    14  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   4003    14  4003    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   4004    4004    15  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   4005    15  4005    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   4006    4006    16  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   5001    17  5001    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   5002    5002    18  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   5003    18  5003    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   5004    5004    19  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   5005    19  5005    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   5006    5006    20  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   6001    21  6001    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   6002    6002    22  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   6003    22  6003    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   6004    6004    23  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   6005    23  6005    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   6006    6006    24  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   7001    25  7001    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   7002    7002    26  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   7003    26  7003    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   7004    7004    27  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   7005    27  7005    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   7006    7006    28  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   8001    29  8001    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   8002    8002    30  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   8003    30  8003    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   8004    8004    31  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   8005    31  8005    $AgBeam $EBc    $IzBc   $IDBeamTransf   ;
element elasticBeamColumn   8006    8006    32  $AgBeam $EBc    $IzBc   $IDBeamTransf   ;


puts "rigid zone assembled"



 
puts "assembling elastic columns"
# define elastic column connection 

element     elasticBeamColumn   1   1001   1011   $AgCol  $Ec $IzCol_5    $IDColTransf        ;
element     elasticBeamColumn   2   1002   1012   $AgCol  $Ec $IzCol_4    $IDColTransf        ;
element     elasticBeamColumn   3   1003   1013   $AgCol  $Ec $IzCol_4    $IDColTransf        ;
element     elasticBeamColumn   4   1004   1014   $AgCol  $Ec $IzCol_5    $IDColTransf        ;
element     elasticBeamColumn   5   1015   1021   $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   6   1016   1022  $AgCol  $Ec $IzCol_3    $IDColTransf        ;
element     elasticBeamColumn   7   1017   1023  $AgCol  $Ec $IzCol_3    $IDColTransf        ;
element     elasticBeamColumn   8   1018   1024  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   9   1025   1031  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   10  1026  1032  $AgCol  $Ec $IzCol_2    $IDColTransf        ;
element     elasticBeamColumn   11  1027  1033  $AgCol  $Ec $IzCol_2    $IDColTransf        ;
element     elasticBeamColumn   12  1028  1034  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   13  1035  1041  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   14  1036  1042  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   15  1037  1043  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   16  1038 1044 $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   17  1045 1051  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   18  1046  1052  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   19  1047  1053  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   20  1048  1054  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   21  1055 1061  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   22  1056  1062  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   23  1057  1063  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   24  1058  1064  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   25  1065  1071  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   26  1066  1072  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   27  1067  1073  $AgCol  $Ec $IzCol_1    $IDColTransf        ;
element     elasticBeamColumn   28  1068  1074  $AgCol  $Ec $IzCol_1    $IDColTransf        ;



#Internal column
set n 11;
set My [expr 547*$kN*$m];                            # Yield moment of column 
set theta_y 0.0042;
set Keff [expr $n*$My/$theta_y]

set intcolTag 1;                 #Integer identifying the material
set Ke $Keff;    #Elastic stiffness
set dp_pos 0.021;  #Pre-capping deformation in positive loading direction
set dpc_pos 0.026;  #Post-capping deformation in positive loading direction
set du_pos 0.047;  #ultimate deformation in positive loading direction
set Fy_pos $My;    #Yield strength in positive loading direction
set FmaxFy_pos 1.02;  #Maximum-to-yield strength ratio in positive loading direction
set FresFy_pos 0.;   #Residual-to-yield strength ratio in positive loading direction
set dp_neg 0.021;   #Pre-capping deformation in negative loading direction
set dpc_neg  0.026;    #Post-capping deformation in negative loading direction
set du_neg 0.047;     #Ultimate deformation in negative loading direction
set Fy_neg  $My;     #Yield strength in negative loading direction
set FmaxFy_neg 1.02;  #Maximum-to-yield strength ratio in negative loading direction
set FresFy_neg  0. ;  #Residual-to-yield strength ratio in negative loading direction
set Lamda_S   10.  ;#Cyclic deterioration parameter for strength deterioration
set Lamda_C   10. ;  #Cyclic deterioration parameter for post-capping strength deterioration
set Lamda_A   10. ;  #Cyclic deterioration parameter for accelerated reloading stiffness deterioration
set Lamda_K   10.;   #Cyclic deterioration parameter for unloading stiffness deterioration
set c_S      1.0 ;   #  rate of strength deterioration. The default value is 1.0 
set c_C      1.0 ;   # rate of post-capping strength deterioration. The default value is 1.0.
set c_A      1.0;    # rate of accelerated reloading deterioration. The default value is 1.0
set c_K      1.0;    #rate of unloading stiffness deterioration. The default value is 1.0
set D_pos  1.0;     #rate of cyclic deterioration in the positive loading direction (this parameter is used to create asymmetric hysteretic behavior for the case of a composite beam). Forsymmetric hysteretic response use 1.0.
set D_neg  1.0;  #rate of cyclic deterioration in the negative loading direction (this parameter is usedto create asymmetric hysteretic behavior for the case of a composite beam). Forsymmetric hysteretic response use 1.0.




uniaxialMaterial IMKPeakOriented $intcolTag $Ke $dp_pos $dpc_pos $du_pos $Fy_pos $FmaxFy_pos $FresFy_pos $dp_neg $dpc_neg $du_neg $Fy_neg $FmaxFy_neg $FresFy_neg $Lamda_S $Lamda_C $Lamda_A $Lamda_K $c_S $c_C $c_A $c_K $D_pos $D_neg

#-------------------------------------------------------------------------------------------------
#External column
set n 11;
set My_e [expr 443*$kN*$m];                            # Yield moment of column 
set theta_y 0.0042;
set Keff_e [expr $n*$My_e/$theta_y]

set extcolTag 2;                 #Integer identifying the material
set Ke_e $Keff_e;    #Elastic stiffness
set dp_pose 0.025;  #Pre-capping deformation in positive loading direction
set dpc_pose 0.032;  #Post-capping deformation in positive loading direction
set du_pose 0.057;  #ultimate deformation in positive loading direction
set Fy_pose $My_e;    #Yield strength in positive loading direction
set FmaxFy_pose 1.02;  #Maximum-to-yield strength ratio in positive loading direction
set FresFy_pose 0.;   #Residual-to-yield strength ratio in positive loading direction
set dp_nege 0.025;   #Pre-capping deformation in negative loading direction
set dpc_nege  0.032;    #Post-capping deformation in negative loading direction
set du_nege 0.057;     #Ultimate deformation in negative loading direction
set Fy_nege  $My_e;     #Yield strength in negative loading direction
set FmaxFy_nege 1.02;  #Maximum-to-yield strength ratio in negative loading direction
set FresFy_nege  0. ;  #Residual-to-yield strength ratio in negative loading direction
set Lamda_S   10.  ;#Cyclic deterioration parameter for strength deterioration
set Lamda_C   10.;  #Cyclic deterioration parameter for post-capping strength deterioration
set Lamda_A   10. ;  #Cyclic deterioration parameter for accelerated reloading stiffness deterioration
set Lamda_K   10.;   #Cyclic deterioration parameter for unloading stiffness deterioration
set c_S      1.0 ;   #  rate of strength deterioration. The default value is 1.0 
set c_C      1.0 ;   # rate of post-capping strength deterioration. The default value is 1.0.
set c_A      1.0;    # rate of accelerated reloading deterioration. The default value is 1.0
set c_K      1.0;    #rate of unloading stiffness deterioration. The default value is 1.0
set D_pos  1.0;     #rate of cyclic deterioration in the positive loading direction (this parameter is used to create asymmetric hysteretic behavior for the case of a composite beam). Forsymmetric hysteretic response use 1.0.
set D_neg  1.0;  #rate of cyclic deterioration in the negative loading direction (this parameter is usedto create asymmetric hysteretic behavior for the case of a composite beam). Forsymmetric hysteretic response use 1.0.




uniaxialMaterial IMKPeakOriented $extcolTag $Ke_e $dp_pose $dpc_pose $du_pose $Fy_pose $FmaxFy_pose $FresFy_pose $dp_nege $dpc_nege $du_nege $Fy_nege $FmaxFy_nege $FresFy_nege $Lamda_S $Lamda_C $Lamda_A $Lamda_K $c_S $c_C $c_A $c_K $D_pos $D_neg




#Beam hinge 
set n 11;
set My_b [expr 800*$kN*$m];                            # Yield moment of column 
set theta_y 0.0042;
set Keffb [expr $n*$My_b/$theta_y]

set beamrotTag 3;                 #Integer identifying the material
set Keb $Keffb;    #Elastic stiffness
set dp_posb 0.025;  #Pre-capping deformation in positive loading direction
set dpc_posb 0.01;  #Post-capping deformation in positive loading direction
set du_posb 0.035;  #ultimate deformation in positive loading direction
set Fy_posb $My_b;    #Yield strength in positive loading direction
set FmaxFy_posb 1.12;  #Maximum-to-yield strength ratio in positive loading direction
set FresFy_posb 0.;   #Residual-to-yield strength ratio in positive loading direction
set dp_negb 0.025;   #Pre-capping deformation in negative loading direction
set dpc_negb  0.01;    #Post-capping deformation in negative loading direction
set du_negb 0.035;     #Ultimate deformation in negative loading direction
set Fy_negb  $My_b;     #Yield strength in negative loading direction
set FmaxFy_negb 1.12;  #Maximum-to-yield strength ratio in negative loading direction
set FresFy_negb  0. ;  #Residual-to-yield strength ratio in negative loading direction
set Lamda_S   0.5  ;#Cyclic deterioration parameter for strength deterioration
set Lamda_C   0.5 ;  #Cyclic deterioration parameter for post-capping strength deterioration
set Lamda_A   0.5 ;  #Cyclic deterioration parameter for accelerated reloading stiffness deterioration
set Lamda_K   0.5;   #Cyclic deterioration parameter for unloading stiffness deterioration
set c_S      1.0 ;   #  rate of strength deterioration. The default value is 1.0 
set c_C      1.0 ;   # rate of post-capping strength deterioration. The default value is 1.0.
set c_A      1.0;    # rate of accelerated reloading deterioration. The default value is 1.0
set c_K      1.0;    #rate of unloading stiffness deterioration. The default value is 1.0
set D_pos  1.0;     #rate of cyclic deterioration in the positive loading direction (this parameter is used to create asymmetric hysteretic behavior for the case of a composite beam). Forsymmetric hysteretic response use 1.0.
set D_neg  1.0;  #rate of cyclic deterioration in the negative loading direction (this parameter is usedto create asymmetric hysteretic behavior for the case of a composite beam). Forsymmetric hysteretic response use 1.0.




uniaxialMaterial IMKPeakOriented $beamrotTag $Keb $dp_posb $dpc_posb $du_posb $Fy_posb $FmaxFy_posb $FresFy_posb $dp_negb $dpc_negb $du_negb $Fy_negb $FmaxFy_negb $FresFy_negb $Lamda_S $Lamda_C $Lamda_A $Lamda_K $c_S $c_C $c_A $c_K $D_pos $D_neg








#Define a stiff material for dof 2
set elasticmattag 5000
set Eemt [expr 30000000*$GPa]

uniaxialMaterial Elastic $elasticmattag $Eemt 

#
#
#Define zerolength element for columns 

#Level 1
set node1   1001    ;
set node2   1002    ;
set node3   1003    ;
set node4   1004    ;
set node5   1011    ;
set node6   1012    ;
set node7   1013    ;
set node8   1014    ;
set node9   1015    ;
set node10  1016    ;
set node11  1017    ;
set node12  1018    ;
set node13  1021    ;
set node14  1022    ;
set node15  1023    ;
set node16  1024    ;
set node17  1025    ;
set node18  1026    ;
set node19  1027    ;
set node20  1028    ;
set node21  1031    ;
set node22  1032    ;
set node23  1033    ;
set node24  1034    ;
set node25  1035    ;
set node26  1036    ;
set node27  1037    ;
set node28  1038    ;
set node29  1041    ;
set node30  1042    ;
set node31  1043    ;
set node32  1044    ;
set node33  1045    ;
set node34  1046    ;
set node35  1047    ;
set node36  1048    ;
set node37  1051    ;
set node38  1052    ;
set node39  1053    ;
set node40  1054    ;
set node41  1055    ;
set node42  1056    ;
set node43  1057    ;
set node44  1058    ;
set node45  1061    ;
set node46  1062    ;
set node47  1063    ;
set node48  1064    ;
set node49  1065    ;
set node50  1066    ;
set node51  1067    ;
set node52  1068    ;
set node53  1071    ;
set node54  1072    ;
set node55  1073    ;
set node56  1074    ;
#

element zeroLength  $node1  1   1001    -mat    $elasticmattag  $elasticmattag  $extcolTag  -dir    1   2   3
element zeroLength  $node2  2   1002    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node3  3   1003    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node4  4   1004    -mat    $elasticmattag  $elasticmattag  $extcolTag  -dir    1   2   3
element zeroLength  $node5  1011    5   -mat    $elasticmattag  $elasticmattag  $extcolTag  -dir    1   2   3
element zeroLength  $node6  1012    6   -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node7  1013    7   -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node8  1014    8   -mat    $elasticmattag  $elasticmattag  $extcolTag  -dir    1   2   3
element zeroLength  $node9  5   1015    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node10 6   1016    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node11 7   1017    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node12 8   1018    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node13 1021    9   -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node14 1022    10  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node15 1023    11  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node16 1024    12  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node17 9   1025    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node18 10  1026    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node19 11  1027    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node20 12  1028    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node21 1031    13  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node22 1032    14  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node23 1033    15  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node24 1034    16  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node25 13  1035    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node26 14  1036    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node27 15  1037    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node28 16  1038    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node29 1041    17  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node30 1042    18  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node31 1043    19  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node32 1044    20  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node33 17  1045    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node34 18  1046    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node35 19  1047    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node36 20  1048    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node37 1051    21  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node38 1052    22  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node39 1053    23  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node40 1054    24  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node41 21  1055    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node42 22  1056    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node43 23  1057    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node44 24  1058    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node45 1061    25  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node46 1062    26  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node47 1063    27  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node48 1064    28  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node49 25  1065    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node50 26  1066    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node51 27  1067    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node52 28  1068    -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node53 1071    29  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node54 1072    30  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node55 1073    31  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
element zeroLength  $node56 1074    32  -mat    $elasticmattag  $elasticmattag  $intcolTag  -dir    1   2   3
#


#Define zero length element for beams 
set node2011    2011    ;
set node2012    2012    ;
set node2013    2013    ;
set node2014    2014    ;
set node2015    2015    ;
set node2016    2016    ;
            
set node3011    3011    ;
set node3012    3012    ;
set node3013    3013    ;
set node3014    3014    ;
set node3015    3015    ;
set node3016    3016    ;
            
set node4011    4011    ;
set node4012    4012    ;
set node4013    4013    ;
set node4014    4014    ;
set node4015    4015    ;
set node4016    4016    ;
            
set node5011    5011    ;
set node5012    5012    ;
set node5013    5013    ;
set node5014    5014    ;
set node5015    5015    ;
set node5016    5016    ;
            
set node6011    6011    ;
set node6012    6012    ;
set node6013    6013    ;
set node6014    6014    ;
set node6015    6015    ;
set node6016    6016    ;
            
set node7011    7011    ;
set node7012    7012    ;
set node7013    7013    ;
set node7014    7014    ;
set node7015    7015    ;
set node7016    7016    ;
            
set node8011    8011    ;
set node8012    8012    ;
set node8013    8013    ;
set node8014    8014    ;
set node8015    8015    ;
set node8016    8016    ;



element zeroLength  $node2011   2001    2011    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node2012   2012    2002    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node2013   2003    2013    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node2014   2014    2004    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node2015   2005    2015    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node2016   2016    2006    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
                                                
element zeroLength  $node3011   3001    3011    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node3012   3012    3002    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node3013   3003    3013    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node3014   3014    3004    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node3015   3005    3015    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node3016   3016    3006    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
                                                
element zeroLength  $node4011   4001    4011    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node4012   4012    4002    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node4013   4003    4013    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node4014   4014    4004    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node4015   4005    4015    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node4016   4016    4006    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
                                                
element zeroLength  $node5011   5001    5011    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node5012   5012    5002    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node5013   5003    5013    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node5014   5014    5004    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node5015   5005    5015    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node5016   5016    5006    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
                                                
element zeroLength  $node6011   6001    6011    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node6012   6012    6002    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node6013   6003    6013    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node6014   6014    6004    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node6015   6005    6015    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node6016   6016    6006    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
                                                
element zeroLength  $node7011   7001    7011    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node7012   7012    7002    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node7013   7003    7013    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node7014   7014    7004    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node7015   7005    7015    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node7016   7016    7006    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
                                                
element zeroLength  $node8011   8001    8011    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node8012   8012    8002    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node8013   8003    8013    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node8014   8014    8004    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node8015   8005    8015    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3
element zeroLength  $node8016   8016    8006    -mat    $elasticmattag  $elasticmattag  $beamrotTag -dir    1   2   3


puts "finished assembling sections"


#Define gravity loadConst

puts "gravity load analysis started"

set UDL [expr -40*$kN/$m]

# GRAVITY LOADS # define gravity load applied to beams and columns -- eleLoad applies loads in local coordinate axis
pattern Plain 1 Linear {
    eleLoad -ele 201 202 203 301 302 303 401 402 403 501 502 503 601 602 603 701 702 703 801 802 803 -type -beamUniform $UDL ; # distributed superstructure-weight on beam
} 
  
#
puts "load distributed on beams"
# ------------------------------------------------- apply gravity load
set Tol 1.0e-4;         # convergence tolerance for test
constraints Plain;          # how it handles boundary conditions
numberer Plain;         # renumber dof's to minimize band-width (optimization), if you want to
system Mumps ICNTL 100;     # how to store and solve the system of equations in the analysis
test NormDispIncr $Tol 20 ;      # determine if convergence has been achieved at the end of an iteration step
algorithm Newton;           # use Newton's solution algorithm: updates tangent stiffness at every iteration
set NstepGravity 100;        # apply gravity in 10 steps
set DGravity [expr 1./$NstepGravity];   # first load increment;
integrator LoadControl $DGravity;   # determine the next time step for an analysis
analysis Static;            # define type of analysis static or transient
puts "fine"
analyze $NstepGravity;      # apply gravity
puts "ok"
# ------------------------------------------------- maintain constant gravity loads and reset time to zero
loadConst -time 0.0

puts "Gravity load applied"


#define DAMPING--------------------------------------------------------------------------------------
puts "Define Damping"
set zeta 0.02; 
set lambda [eigen 3]
set i 0
foreach lam $lambda {
    set i [expr $i+1] 
    puts $lam
	set omega($i) [expr sqrt($lam)]
	puts $omega($i)
}
set a0 [expr $zeta*2.0*$omega(1)*$omega(2)/($omega(1) + $omega(2))]
set a1 [expr $zeta*2.0/($omega(1) + $omega(2))]
puts $a1
puts $a0
rayleigh $a0 $a1 0.0 0.0 
puts "Damping Complete"



